"""Piece geometry for the drop-v1.1 contract.

Rotation zero cells are the reviewed definitions from docs/spec.md.  Orientations
are generated by clockwise rotation (dx,dy) -> (dy,-dx), normalised so the
minimum coordinate on each axis is zero, sorted by (dy,dx), and de-duplicated in
order of first appearance.  They are geometric orientations only (no SRS, no
kicks).
"""
from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache

PIECE_NAMES = ("I", "O", "T", "S", "Z", "J", "L")

BASE_CELLS = {
    0: ((0, 0), (1, 0), (2, 0), (3, 0)),  # I
    1: ((0, 0), (1, 0), (0, 1), (1, 1)),  # O
    2: ((0, 0), (1, 0), (2, 0), (1, 1)),  # T
    3: ((0, 0), (1, 0), (1, 1), (2, 1)),  # S
    4: ((1, 0), (2, 0), (0, 1), (1, 1)),  # Z
    5: ((0, 0), (1, 0), (2, 0), (0, 1)),  # J
    6: ((0, 0), (1, 0), (2, 0), (2, 1)),  # L
}

W = 10
H = 20
MAX_ROTATIONS = 4
MAX_CANDIDATE_ID = 40


def _normalise(cells):
    min_x = min(x for x, _ in cells)
    min_y = min(y for _, y in cells)
    return tuple(sorted(((x - min_x, y - min_y) for x, y in cells), key=lambda c: (c[1], c[0])))


@lru_cache(maxsize=None)
def rotations(piece_id: int):
    """Unique orientations of a piece, each a tuple of four (dx,dy) cells."""
    if piece_id not in BASE_CELLS:
        raise ValueError(f"invalid piece id {piece_id}")
    out = []
    cells = list(BASE_CELLS[piece_id])
    for _ in range(MAX_ROTATIONS):
        norm = _normalise(cells)
        if norm not in out:
            out.append(norm)
        cells = [(dy, -dx) for dx, dy in cells]
    return tuple(out)


@dataclass(frozen=True)
class Shape:
    piece_id: int
    rotation: int
    cells: tuple            # four (dx,dy), sorted by (dy,dx)
    width: int
    height: int
    bottom: tuple           # bottom[dx] = min dy in column dx (0 for unoccupied columns)
    colmask: int            # bit dx set when column dx of the bounding box is occupied
    colbits: tuple          # colbits[dx] = bitmask over dy of cells in column dx

    @property
    def candidate_base(self) -> int:
        return 10 * self.rotation


@lru_cache(maxsize=None)
def shape(piece_id: int, rotation: int) -> Shape:
    rots = rotations(piece_id)
    if not 0 <= rotation < len(rots):
        raise ValueError(f"piece {piece_id} has no rotation {rotation}")
    cells = rots[rotation]
    width = max(x for x, _ in cells) + 1
    height = max(y for _, y in cells) + 1
    bottom = []
    colbits = []
    colmask = 0
    for dx in range(4):
        col = [dy for cx, dy in cells if cx == dx]
        if col:
            colmask |= 1 << dx
            bottom.append(min(col))
            colbits.append(sum(1 << dy for dy in col))
        else:
            bottom.append(0)
            colbits.append(0)
    return Shape(piece_id, rotation, cells, width, height, tuple(bottom), colmask, tuple(colbits))


def rotation_count(piece_id: int) -> int:
    return len(rotations(piece_id))


def decode_candidate(candidate_id: int):
    """candidate_id = 10*rotation + x."""
    return candidate_id // 10, candidate_id % 10


def is_valid_candidate(piece_id: int, candidate_id: int) -> bool:
    if not 0 <= candidate_id < MAX_CANDIDATE_ID:
        return False
    rotation, x = decode_candidate(candidate_id)
    if rotation >= rotation_count(piece_id):
        return False
    return x + shape(piece_id, rotation).width <= W


@lru_cache(maxsize=None)
def candidate_ids(piece_id: int):
    """Dense list of geometrically valid candidate IDs in increasing order."""
    return tuple(c for c in range(MAX_CANDIDATE_ID) if is_valid_candidate(piece_id, c))


def all_candidates():
    """(piece_id, rotation, x) for every geometric candidate of every piece: 162 entries."""
    out = []
    for piece_id in range(7):
        for cid in candidate_ids(piece_id):
            rotation, x = decode_candidate(cid)
            out.append((piece_id, rotation, x))
    return out
