"""Long piece streams for the v2 quality protocol (U15, guide §9.4).

The v1 streams (model/streams.py: 2,001 pieces, seeds 1000-1049 / 2000-2019 / 3000-3099, JSON)
are untouched.  v2 streams are the same seven-bag generator (`model.streams.seven_bag`, one
`random.Random(seed)` per stream, shuffle of [0..6] repeated) run to 50,001 pieces — 50,000
decisions plus one preview — and stored as one byte per piece under benchmarks/streams_v2/
(gzip-compressed, values 0-6) with a manifest of content hashes.  The hash is over the decoded
piece bytes, so it is independent of the compression and of the JSON representation used by v1.
Splits are disjoint from every v1 split; the module checks that at import.

    python tools/streams_v2.py generate --split v2_development    # write files + manifest entries
    python tools/streams_v2.py check                              # every manifest entry re-hashed
    python tools/streams_v2.py decode 10000 --head 20             # readable decoder
"""
from __future__ import annotations

import gzip
import hashlib
import json
from pathlib import Path

from .streams import SPEC_ID, SPLITS as V1_SPLITS, seven_bag

STREAM_LENGTH_V2 = 50_001          # 50,000 decisions + one preview
GENERATOR_V2 = "python-random-seven-bag"   # identical generator to v1, longer streams

SPLITS_V2 = {
    "v2_development": range(10000, 10020),   # 20 streams: pilots, wall-time and cap estimates
    "v2_heldout": range(20000, 20100),       # 100 streams: the frozen primary study
    "v2_iid_heldout": range(30000, 30100),   # reserved for the optional quality-v2-iid suite (not generated by default)
}

for _name, _rng in SPLITS_V2.items():
    for _v1name, _v1rng in V1_SPLITS.items():
        assert not (set(_rng) & set(_v1rng)), f"v2 split {_name} overlaps v1 split {_v1name}"
_all = [s for r in SPLITS_V2.values() for s in r]
assert len(_all) == len(set(_all)), "v2 splits overlap each other"

PIECE_NAMES = ("I", "O", "T", "S", "Z", "J", "L")


def streams_dir(root: Path) -> Path:
    return root / "benchmarks" / "streams_v2"


def manifest_path(root: Path) -> Path:
    return streams_dir(root) / "manifest.json"


def stream_file(root: Path, seed: int) -> Path:
    return streams_dir(root) / f"stream_{seed}.bin.gz"


def split_of_v2(seed: int) -> str:
    for name, rng in SPLITS_V2.items():
        if seed in rng:
            return name
    return "adhoc"


def piece_bytes(pieces) -> bytes:
    b = bytes(pieces)
    if any(x > 6 for x in b):
        raise ValueError("piece ids must be 0..6")
    return b


def content_sha256(pieces_or_bytes) -> str:
    """Hash of the decoded one-byte-per-piece content (representation independent)."""
    data = pieces_or_bytes if isinstance(pieces_or_bytes, (bytes, bytearray)) else piece_bytes(pieces_or_bytes)
    return hashlib.sha256(bytes(data)).hexdigest()


def generate_pieces(seed: int, length: int = STREAM_LENGTH_V2) -> bytes:
    return piece_bytes(seven_bag(seed, length))


def load_manifest(root: Path) -> dict:
    p = manifest_path(root)
    if not p.is_file():
        return {"schema": "stream-manifest-v2", "spec": SPEC_ID, "generator": GENERATOR_V2, "length": STREAM_LENGTH_V2,
                "splits": {k: [v.start, v.stop - 1] for k, v in SPLITS_V2.items()}, "encoding": "one byte per piece (0-6), gzip file",
                "streams": {}}
    return json.loads(p.read_text())


def write_manifest(root: Path, doc: dict) -> None:
    p = manifest_path(root)
    p.parent.mkdir(parents=True, exist_ok=True)
    doc["streams"] = dict(sorted(doc["streams"].items(), key=lambda kv: int(kv[0])))
    tmp = p.with_suffix(".json.part")
    tmp.write_text(json.dumps(doc, indent=1) + "\n")
    tmp.replace(p)


def write_stream_v2(root: Path, seed: int, length: int = STREAM_LENGTH_V2, manifest: dict | None = None) -> dict:
    data = generate_pieces(seed, length)
    path = stream_file(root, seed)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".part")
    with open(tmp, "wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", compresslevel=9, fileobj=raw, mtime=0) as fh:   # mtime 0: byte-identical files
            fh.write(data)
    tmp.replace(path)
    entry = {"seed": seed, "split": split_of_v2(seed), "length": len(data), "sha256": content_sha256(data),
             "file": str(path.relative_to(root)), "file_sha256": hashlib.sha256(path.read_bytes()).hexdigest()}
    if manifest is not None:
        manifest["streams"][str(seed)] = entry
    return entry


def load_stream_v2(root: Path, seed: int, manifest: dict | None = None) -> dict:
    """Decode a v2 stream and verify it against the manifest.  Returns the same shape as
    model.streams.load_stream: {'spec', 'seed', 'split', 'length', 'sha256', 'pieces'} plus 'generator'."""
    manifest = manifest if manifest is not None else load_manifest(root)
    entry = manifest["streams"].get(str(seed))
    if entry is None:
        raise FileNotFoundError(f"v2 stream {seed} is not in {manifest_path(root)}; generate it first")
    path = root / entry["file"]
    if not path.is_file():
        raise FileNotFoundError(f"v2 stream file missing: {path}")
    with gzip.open(path, "rb") as fh:
        data = fh.read()
    if len(data) != entry["length"] or content_sha256(data) != entry["sha256"]:
        raise ValueError(f"v2 stream {seed}: content hash/length mismatch with the manifest")
    if any(x > 6 for x in data):
        raise ValueError(f"v2 stream {seed}: piece id out of range")
    return {"spec": manifest["spec"], "seed": seed, "split": entry["split"], "length": len(data), "sha256": entry["sha256"],
            "generator": manifest["generator"], "pieces": list(data)}


def check_manifest(root: Path) -> list[str]:
    """Re-hash every manifest entry; returns problems (empty = OK)."""
    problems = []
    m = load_manifest(root)
    if m.get("schema") != "stream-manifest-v2":
        problems.append("manifest schema is not stream-manifest-v2")
    for seed_s, entry in m.get("streams", {}).items():
        seed = int(seed_s)
        try:
            doc = load_stream_v2(root, seed, m)
        except (FileNotFoundError, ValueError) as exc:
            problems.append(str(exc))
            continue
        if doc["split"] != split_of_v2(seed):
            problems.append(f"stream {seed}: split {doc['split']} != {split_of_v2(seed)}")
        if entry["file_sha256"] != hashlib.sha256((root / entry["file"]).read_bytes()).hexdigest():
            problems.append(f"stream {seed}: file hash changed (content still verifies)")
        if seed in SPLITS_V2["v2_development"] or seed in SPLITS_V2["v2_heldout"]:
            # deterministic regeneration must reproduce the committed content
            if content_sha256(generate_pieces(seed, doc["length"])) != doc["sha256"]:
                problems.append(f"stream {seed}: regeneration does not reproduce the committed content")
    return problems


def decode_names(pieces, head: int | None = None) -> str:
    sel = pieces if head is None else pieces[:head]
    return " ".join(PIECE_NAMES[p] for p in sel)
