# Hardware sources in dependency order (generated .svh files are included, not compiled)
rtl/shape_rom.sv
rtl/cand_rom.sv
rtl/score.sv
rtl/board_profile.sv
rtl/drop_unit.sv
rtl/merge_unit.sv
rtl/line_clear.sv
rtl/features.sv
rtl/drop_fast.sv
rtl/merge_fast.sv
rtl/features_fast.sv
rtl/candidate_eval.sv
rtl/lane_player.sv
rtl/search_depth2.sv
rtl/rank_level.sv
rtl/row_rank20.sv
rtl/rank_match.sv
rtl/row_select_groups.sv
rtl/row_select_final.sv
rtl/drop_merge_pipe.sv
rtl/line_clear_pipe.sv
rtl/features_pipe.sv
rtl/score_pipe.sv
rtl/candidate_pipe.sv
rtl/search_pipeline.sv
rtl/tetris_core.sv
rtl/stream_wrapper.sv
