# tetromino-circuit — every recipe runs through scripts/env.sh so fresh shells need no activation.
SHELL := /bin/bash
ENV := bash scripts/env.sh
PY := $(ENV) python
PYTEST_ARGS ?=
RUN_RTL := $(PY) tools/run_rtl.py

# Hardware/policy configuration (validated by model/config.py in every tool)
ARCH ?= 0
BOARD_REPR ?= 0
LANES ?= 1
DEPTH ?= 1
PRECISION ?= 0
SEED ?= 1
FREQ ?= 50
CAP ?= 250
COUNT ?= 50
DRIVER ?= native
CFG := --arch $(ARCH) --board-repr $(BOARD_REPR) --lanes $(LANES) --depth $(DEPTH) --precision $(PRECISION)
PARAMS := --param ARCH=$(ARCH) --param BOARD_REPR=$(BOARD_REPR) --param LANES=$(LANES) --param DEPTH=$(DEPTH) --param PRECISION=$(PRECISION)
# Configuration ids are generated by model/config.py only (never spelled textually here)
CFG_ID := $(shell $(PY) -m model.config $(ARCH) $(BOARD_REPR) $(LANES) $(DEPTH) $(PRECISION))

.PHONY: help doctor doctor-python gen check-gen smoke test-python test-geometry test-reference \
        demo-python tournament-python pilot-python streams \
        test-shapes test-score test-drop test-merge test-clear test-features test-candidate synth-candidate \
        test-core test-protocol native test-driver replay-suite demo-rtl test-wrapper synth pnr \
        test-fast test-cache test-precision measure-precision test-lookahead-reference test-lookahead-rtl \
        test-lanes test-rtl check-benchmark-config bench-pilot bench measure-matrix tournament plots \
        check-report check-release reproduce clean \
        test-identities test-result-schemas check-v1-results upgrade-smoke matrix-plan matrix-status \
        print-cfg-id check-a2-spec test-prefix test-compactor-native formal-compactor formal-smoke \
        test-compactor-pipe synth-compactor-pipe test-drop-merge-pipe test-features-pipe test-score-pipe \
        test-a2-stream test-a2-metadata test-a2-reset test-a2-pipe synth-a2-pipe \
        test-a2-core-extra test-request-interval corpus-v2-dev \
        test-reducer verify-a2-release formal-a2-control mutation-check-a2 regress-a0-a1 route-a2-dev

help:
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-28s %s\n", $$1, $$2}'

# ---------------------------------------------------------------- E00
doctor: ## full toolchain check (hardware gate)
	$(PY) tools/doctor.py --profile full
doctor-python: ## python-only check
	$(PY) tools/doctor.py --profile python
smoke: ## counter simulation, lint and synthesis smoke test
	$(RUN_RTL) --top counter --test tb_counter --source rtl/learning/counter.sv
	$(ENV) verilator --lint-only -Wall --top-module counter rtl/learning/counter.sv
	mkdir -p build/smoke && $(ENV) yosys -q -l build/smoke/counter_synth.log -p 'read_verilog -sv rtl/learning/counter.sv; synth_ecp5 -top counter; stat; check -assert' > /dev/null
	$(PY) tools/check_synth_log.py build/smoke/counter_synth.log --min-cells 4

# ---------------------------------------------------------------- E01–E03
gen: ## regenerate geometry tables and verify determinism
	$(PY) tools/gen_shapes.py
	$(PY) tools/gen_shapes.py --check
check-gen:
	$(PY) tools/gen_shapes.py --check
streams: ## regenerate the committed piece streams
	$(PY) tools/make_streams.py
	$(PY) tools/make_streams.py --check
test-geometry: ## E01 gate
	$(PY) -m pytest tests/unit/test_pieces.py tests/unit/test_board.py -q $(PYTEST_ARGS)
test-reference: ## E02 gate: 40,500-case three-way differential and policy equivalence
	$(PY) -m pytest tests/unit/test_game.py tests/unit/test_reference.py tests/unit/test_policy.py -q $(PYTEST_ARGS)
test-bootstrap: ## U01: mocked-platform bootstrap tests
	$(PY) -m pytest tests/unit/test_bootstrap.py -q $(PYTEST_ARGS)
test-python: ## all pure-Python tests
	$(PY) -m pytest tests/unit -q $(PYTEST_ARGS)
demo-python: ## software replay and GIF (seed 2000, 250 pieces)
	$(PY) tools/play.py --backend python --policy heuristic --seed 2000 --max-pieces 250 --out results/python_demo.jsonl
	$(PY) tools/play.py --backend python --policy random_legal --seed 2000 --max-pieces 250 --out results/random_demo.jsonl
	$(PY) tools/render.py --replay results/python_demo.jsonl --out assets/python_demo.gif --png assets/python_demo_final.png
tournament-python: demo-python ## two-policy software tournament
	$(PY) tools/render_tournament.py --replays results/python_demo.jsonl results/random_demo.jsonl --sync pieces --out assets/tournament_python.gif --max-frames 120
pilot-python: ## validation pilot, 20 seeds, cap 500
	$(PY) tools/pilot.py --split validation --cap 500 --out results/pilot_validation.csv

# ---------------------------------------------------------------- E04–E06 (module tests)
test-shapes: ## shape ROM vs Python, all 32 inputs
	$(RUN_RTL) --top shape_rom --test tb_shapes --files-f rtl/files_shapes.f
test-score: ## registered scorer vs Python (PRECISION=$(PRECISION))
	$(RUN_RTL) --top score --test tb_score --files-f rtl/files_score.f --param PRECISION=$(PRECISION)
test-drop:
	$(RUN_RTL) --top drop_unit --test tb_drop --files-f rtl/files_drop.f
test-merge:
	$(RUN_RTL) --top merge_unit --test tb_merge --files-f rtl/files_merge.f
test-clear:
	$(RUN_RTL) --top line_clear --test tb_clear --files-f rtl/files_clear.f
test-features:
	$(RUN_RTL) --top features --test tb_features --files-f rtl/files_features.f --param PRECISION=$(PRECISION)
test-candidate: ## A0/A1 candidate evaluator with intermediate-value checks
	$(RUN_RTL) --top candidate_eval --test tb_candidate --files-f rtl/files_candidate$(if $(filter 0,$(ARCH)),_a0,).f --param ARCH=$(ARCH) --param BOARD_REPR=$(BOARD_REPR) --param PRECISION=$(PRECISION)
synth-candidate:
	$(PY) tools/synth.py --top candidate_eval --arch $(ARCH) --board-repr $(BOARD_REPR) --precision $(PRECISION) --out build/synth_candidate_a$(ARCH)

# ---------------------------------------------------------------- E07–E09 (core)
test-core: ## differential core tests, COUNT requests, DRIVER=cocotb|native
	$(PY) tools/test_core.py $(CFG) --count $(COUNT) --driver $(DRIVER)
test-protocol: ## ready/valid, stalls, resets, invalid piece
	$(RUN_RTL) --top tetris_core --test tb_protocol --files-f rtl/files.f $(PARAMS)
native: ## build the persistent C++ Verilator driver (build/native/<native_key>, alias build/native_<id>)
	$(PY) tools/build_native.py $(CFG) --out build/native_$(CFG_ID)
test-driver: ## native vs cocotb equivalence on COUNT requests
	$(PY) tools/test_core.py $(CFG) --count $(COUNT) --driver both
replay-suite: ## seeds 2000-2002 with the RTL core, checked against Python at every move
	$(PY) tools/play_rtl.py $(CFG) --driver native --seed 2000 --max-pieces $(CAP) --out results/replays/$(CFG_ID)_seed2000_cap$(CAP).jsonl
	$(PY) tools/play_rtl.py $(CFG) --driver native --seed 2001 --max-pieces $(CAP) --out results/replays/$(CFG_ID)_seed2001_cap$(CAP).jsonl
	$(PY) tools/play_rtl.py $(CFG) --driver native --seed 2002 --max-pieces $(CAP) --out results/replays/$(CFG_ID)_seed2002_cap$(CAP).jsonl
demo-rtl: ## default RTL replay GIF (A0, seed 2000)
	$(PY) tools/play_rtl.py $(CFG) --driver native --seed 2000 --max-pieces $(CAP) --out results/rtl_demo.jsonl
	$(PY) tools/render.py --replay results/rtl_demo.jsonl --out assets/rtl_demo.gif --png assets/rtl_demo_final.png
test-wrapper: ## streaming wrapper framing, stalls, reset, back-to-back
	$(RUN_RTL) --top stream_wrapper --test tb_wrapper --files-f rtl/files.f $(PARAMS)
synth: ## Yosys synth_ecp5 of stream_wrapper (build/synth/<synth_key>, alias build/synth_<id>)
	$(PY) tools/synth.py --top stream_wrapper $(CFG) --out build/synth_$(CFG_ID)
pnr: ## nextpnr-ecp5 85k CABGA381 speed 6 at FREQ MHz, SEED; record under results/v2/raw/routes/<route_key>.json
	$(PY) tools/pnr.py $(CFG) --seed $(SEED) --freq $(FREQ)

# ---------------------------------------------------------------- E10–E15
test-fast: ## A1 datapath modules vs oracle
	$(RUN_RTL) --top fast_tb --test tb_fast --files-f rtl/files_fast.f
test-cache:
	$(RUN_RTL) --top tetris_core --test tb_cache --files-f rtl/files.f --param ARCH=1 --param BOARD_REPR=1
test-precision: ## every profile against its own reference (scorer tuples + full requests)
	$(PY) tools/test_precision.py
measure-precision:
	$(PY) tools/measure_precision.py --split validation
test-lookahead-reference:
	$(PY) -m pytest tests/unit/test_lookahead.py -q $(PYTEST_ARGS)
test-lookahead-rtl:
	$(RUN_RTL) --top tetris_core --test tb_lookahead --files-f rtl/files.f --param ARCH=1 --param BOARD_REPR=1 --param DEPTH=2
	$(RUN_RTL) --top tetris_core --test tb_lookahead --files-f rtl/files.f --param ARCH=1 --param BOARD_REPR=1 --param DEPTH=1 --build-tag d1preview
test-lanes: ## LANES=2|4: ownership, cross-lane ties, strict last-finishing winner, per-lane counters (results/v2/lanes/)
	$(RUN_RTL) --top tetris_core --test tb_lanes --files-f rtl/files.f --param ARCH=1 --param BOARD_REPR=1 --param LANES=$(if $(filter 1,$(LANES)),2,$(LANES))
test-rtl: test-shapes test-score test-drop test-merge test-clear test-features test-candidate test-protocol ## directed RTL tests plus a differential subset
	$(PY) tools/test_core.py --arch 0 --board-repr 0 --count 100 --driver native

# ---------------------------------------------------------------- E16–E19
check-benchmark-config:
	$(PY) tools/bench.py --check-config
bench-pilot:
	$(PY) tools/bench.py --suite pilot
bench: ## frozen software study, SUITE=precision|depth
	$(PY) tools/bench.py --suite $(SUITE)
measure-matrix: ## v2 matrix runner: requires MANIFEST=benchmarks/<matrix>.json (never runs a full study by default)
	@test -n "$(MANIFEST)" || { echo "usage: make measure-matrix MANIFEST=benchmarks/hardware_v2.json (smoke preset: make upgrade-smoke)"; exit 2; }
	$(PY) tools/measure_matrix.py run --manifest $(MANIFEST)
matrix-plan: ## dry run of MANIFEST: jobs, route keys, reuse
	@test -n "$(MANIFEST)" || { echo "usage: make matrix-plan MANIFEST=benchmarks/<matrix>.json"; exit 2; }
	$(PY) tools/measure_matrix.py plan --manifest $(MANIFEST)
matrix-status: ## runner lock, heartbeat and raw record counts
	$(PY) tools/measure_matrix.py status
tournament: ## real RTL tournament replays and GIF
	$(PY) tools/tournament.py
plots:
	$(PY) tools/plots.py
check-report:
	$(PY) tools/check_report.py
check-release:
	$(PY) tools/check_release.py

print-cfg-id: ## configuration id for ARCH/BOARD_REPR/LANES/DEPTH/PRECISION (from model/config.py)
	@echo $(CFG_ID)

# ---------------------------------------------------------------- U02 (identities, resume, summaries, gates)
test-identities: ## U02: canonical identities and the invalidation matrix
	$(PY) -m pytest tests/unit/test_identity.py -q $(PYTEST_ARGS)
test-result-schemas: ## U02: route/quality records, status classification, single-identity summaries, gates, runner
	$(PY) -m pytest tests/unit/test_result_schemas.py tests/unit/test_runner.py tests/unit/test_bench_v2.py -q $(PYTEST_ARGS)
check-v1-results: ## U02: frozen v1 experiment validated by exact expected-job membership
	$(PY) tools/check_v1_results.py
upgrade-smoke: ## U02: short development preset — one real route + 50-state corpus + tiny v2 quality suite (resumable)
	$(PY) tools/measure_matrix.py run --manifest benchmarks/smoke_v2.json
	$(PY) tools/bench.py --suite smoke --config benchmarks/quality_smoke_v2.json --out-root results/v2

# ---------------------------------------------------------------- U05 (parallel compactor)
MODE ?= exhaustive
test-prefix: ## U05: prefix/select reference vs local list filter, level structure, fixtures, random boards
	$(PY) -m pytest tests/unit/test_compaction.py -q $(PYTEST_ARGS)
test-compactor-native: ## U05/U06: native harness on the actual HDL, MODE=exhaustive|random|stream (COUNT, SEED)
	$(PY) tools/compactor_native.py --mode $(MODE) --count $(COUNT) --seed $(SEED)
formal-smoke: ## SBY/solver/syntax smoke proof with the pinned suite
	$(PY) tools/formal.py smoke
formal-compactor: formal-smoke ## U05: unbounded miter proof (DUT vs independent filter) and extreme-case covers
	$(PY) tools/formal.py compactor
	$(PY) tools/formal.py compactor_cover

# ---------------------------------------------------------------- U06 (pipelined compactor)
test-compactor-pipe: ## U06: cocotb streaming/stall/bubble/reset tests of line_clear_pipe behind its ready/valid harness
	$(RUN_RTL) --top line_clear_pipe_harness --test tb_clear_pipe --files-f rtl/files_compactor_pipe.f
synth-compactor-pipe: ## U06: micro-synthesis of line_clear_pipe: no latch/DSP, register scale, selection logic live
	$(PY) tools/synth_module.py --top line_clear_pipe --files-f rtl/files_compactor_pipe.f --expect-no-latch --expect-no-dsp --expect-ff-min 3000 --expect-ff-max 4200 --expect-lut-min 2000
	$(PY) tools/synth_module.py --top line_clear_pipe --files-f rtl/files_compactor_pipe.f --noflatten --expect-module-live rank_match --expect-module-live row_select_groups --expect-module-live row_select_final

# ---------------------------------------------------------------- U07 (landing/merge front end)
test-drop-merge-pipe: ## U07: P0-P3 geometry (40,500 corpus tokens), fixtures, stream/stall/reset; smoke synthesis without latch/DSP
	$(RUN_RTL) --top drop_merge_pipe_harness --test tb_drop_merge_pipe --files-f rtl/files_drop_merge_pipe.f
	$(PY) tools/synth_module.py --top drop_merge_pipe --files-f rtl/files_drop_merge_pipe.f --expect-no-latch --expect-no-dsp --expect-ff-min 200

# ---------------------------------------------------------------- U08 (feature and score pipelines)
test-features-pipe: ## U08: P13-P19 vs direct hole counting (one-hots, height-20 columns, 10,000 boards), stalls, reset; smoke synthesis
	$(RUN_RTL) --top features_pipe_harness --test tb_features_pipe --files-f rtl/files_features_pipe.f
	$(PY) tools/synth_module.py --top features_pipe --files-f rtl/files_features_pipe.f --expect-no-latch --expect-no-dsp --expect-ff-min 300
test-score-pipe: ## U08: P20-P22 at every bound, 10,000 tuples, signed scores, illegal canonicalization; smoke synthesis
	$(RUN_RTL) --top score_pipe_harness --test tb_score_pipe --files-f rtl/files_score_pipe.f
	$(PY) tools/synth_module.py --top score_pipe --files-f rtl/files_score_pipe.f --expect-no-latch --expect-no-dsp --expect-ff-min 100

# ---------------------------------------------------------------- U09 (candidate pipeline)
A2_CONTEXTS ?= 60
test-a2-pipe: ## U09: cocotb protocol checks of candidate_pipe (latency 22/23, freeze, illegal order, reset)
	$(RUN_RTL) --top candidate_pipe --test tb_candidate_pipe --files-f rtl/files_candidate_pipe.f
test-a2-stream: test-a2-pipe ## U09: 4,096 consecutive tokens (spacing 1, visible 22, transfer 23) + oracle traffic with bubbles/stalls
	$(PY) tools/a2_native.py --phase stream --contexts $(A2_CONTEXTS)
	$(PY) tools/a2_native.py --phase traffic --contexts $(A2_CONTEXTS)
test-a2-metadata: ## U09: identical candidates with distinct tags, rotation/x changing every cycle, last on an illegal token
	$(PY) tools/a2_native.py --phase metadata --contexts $(A2_CONTEXTS)
test-a2-reset: ## U09: reset at every occupancy (stalled and not), at last issue and just before retirement; bounded trace
	$(PY) tools/a2_native.py --phase reset --contexts $(A2_CONTEXTS)
	$(PY) tools/a2_native.py --phase reset --contexts $(A2_CONTEXTS) --trace build/traces/a2_stall_reset.vcd
synth-a2-pipe: ## U09: micro-synthesis of candidate_pipe (no latch/DSP)
	$(PY) tools/synth_module.py --top candidate_pipe --files-f rtl/files_candidate_pipe.f --expect-no-latch --expect-no-dsp --expect-ff-min 4000

# ---------------------------------------------------------------- U10 (search + core integration)
corpus-v2-dev: ## U10: regenerate the 2,000-state development corpus (seeds 11000-11099) and its sidecar
	$(PY) tools/make_corpus_v2.py --out benchmarks/states/corpus_d1_upgrade_dev.jsonl --seed-base 11000
test-a2-core-extra: ## U10: A2 whole-core equivalence on the 2,000-state development corpus (native), with category coverage
	$(PY) tools/test_core.py --arch 2 --board-repr 1 --count 2000 --driver native --corpus benchmarks/states/corpus_d1_upgrade_dev.jsonl --out build/decisions/a2-cache-d1-p0-l1_native_dev2000.csv
test-request-interval: ## U10: two real acceptance edges per pair (batch mode) vs the inferred interval and, for A2, D(N)=N+29 / R(N)=N+31
	$(PY) tools/request_interval.py $(CFG) --count 200

# ---------------------------------------------------------------- U11 (verification and mutations)
test-reducer: ## U11 (V10): reducer winner hazards in cocotb (all illegal, one legal, last wins, ties, signed, shadow model)
	$(RUN_RTL) --top best_reducer --test tb_best_reducer --files-f rtl/files_reducer.f
regress-a0-a1: ## U11: targeted regression of the v1 configurations after the top-level change
	$(MAKE) test-rtl
	$(PY) tools/test_core.py --arch 1 --board-repr 1 --lanes 2 --count 200 --driver native
	$(PY) tools/test_core.py --arch 1 --board-repr 1 --depth 2 --count 100 --driver native
	$(MAKE) test-cache
	$(MAKE) test-lanes
	$(MAKE) test-lookahead-rtl
verify-a2-release: ## U11: V01-V14 for A2 (spec, compactor, front end, features, scorer, streams, core, protocol, drivers, replays) + A0/A1 regression
	$(MAKE) check-a2-spec
	$(MAKE) test-prefix
	$(MAKE) test-compactor-native MODE=exhaustive
	$(MAKE) test-compactor-native MODE=random COUNT=100000 SEED=3
	$(MAKE) test-compactor-pipe
	$(MAKE) test-compactor-native MODE=stream COUNT=4096 SEED=1
	$(MAKE) test-drop-merge-pipe
	$(MAKE) test-features-pipe
	$(MAKE) test-score-pipe
	$(MAKE) test-a2-stream
	$(MAKE) test-a2-metadata
	$(MAKE) test-a2-reset
	$(MAKE) test-reducer
	$(MAKE) test-core ARCH=2 BOARD_REPR=1 LANES=1 DEPTH=1 PRECISION=0 COUNT=1000 DRIVER=native
	$(MAKE) test-a2-core-extra
	$(MAKE) test-protocol ARCH=2 BOARD_REPR=1
	$(MAKE) test-wrapper ARCH=2 BOARD_REPR=1
	$(MAKE) test-driver ARCH=2 BOARD_REPR=1 COUNT=50
	$(MAKE) test-request-interval ARCH=2 BOARD_REPR=1
	$(MAKE) replay-suite ARCH=2 BOARD_REPR=1 LANES=1 DEPTH=1 PRECISION=0 CAP=250
	$(MAKE) regress-a0-a1
formal-a2-control: ## U11: control-conservation (abstract pipeline) and best-reduction proofs with covers
	$(PY) tools/formal.py smoke
	$(PY) tools/formal.py control
	$(PY) tools/formal.py control_cover
	$(PY) tools/formal.py reducer
	$(PY) tools/formal.py reducer_cover
mutation-check-a2: ## U11: twelve deliberate mutations, each killed by a named behavioural test, sources restored
	$(PY) tools/run_mutations.py

# ---------------------------------------------------------------- U12 (route A2)
route-a2-dev: ## U12: synthesize the A2 wrapper (-nodsp), inspect the hierarchy, one development route at FREQ MHz seed SEED
	$(PY) tools/synth.py --top stream_wrapper --arch 2 --board-repr 1 --dsp-policy nodsp
	$(PY) tools/synth_module.py --top stream_wrapper --files-f rtl/files.f --param ARCH=2 --param BOARD_REPR=1 --param LANES=1 --param DEPTH=1 --param PRECISION=0 --noflatten --expect-no-latch --expect-no-dsp --expect-module-live candidate_pipe --expect-module-live search_pipeline
	$(PY) tools/pnr.py --arch 2 --board-repr 1 --seed $(SEED) --freq $(FREQ) --dsp-policy nodsp --timeout 600

# ---------------------------------------------------------------- U04 (A2 specification)
check-a2-spec: ## U04/U13: stage manifest, configuration identity, cycle contract, A2 and four-lane elaboration guards
	$(PY) -m pytest tests/unit/test_a2_spec.py -q $(PYTEST_ARGS)
	$(PY) tools/check_a2_spec.py --rtl
reproduce: ## resumable orchestrator of the documented release pipeline
	$(PY) tools/reproduce.py
clean:
	rm -rf build/*
