#!/usr/bin/env python3
"""Regenerate the shared Python/RTL piece geometry; a second run should be a no-op."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from model.pieces import PIECE_NAMES, candidate_ids, rotations, shape  # noqa: E402

HEADER = "// Generated by tools/gen_shapes.py from model/pieces.py. Do not edit.\n"


def shapes_doc():
    pieces = []
    for pid in range(7):
        rots = []
        for r in range(len(rotations(pid))):
            s = shape(pid, r)
            rots.append({"rotation": r, "cells": [list(c) for c in s.cells], "width": s.width,
                         "height": s.height, "bottom": list(s.bottom), "colmask": s.colmask,
                         "colbits": list(s.colbits)})
        pieces.append({"id": pid, "name": PIECE_NAMES[pid], "rotations": rots,
                       "candidate_ids": list(candidate_ids(pid))})
    return {"spec": "drop-v1.1", "pieces": pieces, "total_candidates": sum(len(candidate_ids(p)) for p in range(7))}


def shape_case() -> str:
    lines = [HEADER, "// {piece[2:0], rot[1:0]} -> dx, dy (2 bits per cell, cell k at [2k+:2]), width, height,",
             "// bottom offsets (2 bits per column), occupied-column mask, valid.", ""]
    for pid in range(7):
        for r in range(len(rotations(pid))):
            s = shape(pid, r)
            dx = sum(c[0] << (2 * k) for k, c in enumerate(s.cells))
            dy = sum(c[1] << (2 * k) for k, c in enumerate(s.cells))
            bottom = sum(b << (2 * k) for k, b in enumerate(s.bottom))
            lines.append(
                f"    5'b{pid:03b}_{r:02b}: begin // {PIECE_NAMES[pid]} rot {r} cells {list(s.cells)}\n"
                f"        dx_o = 8'h{dx:02x}; dy_o = 8'h{dy:02x}; width_o = 3'd{s.width}; height_o = 3'd{s.height};\n"
                f"        bottom_o = 8'h{bottom:02x}; colmask_o = 4'b{s.colmask:04b}; valid_o = 1'b1;\n"
                f"    end"
            )
    lines.append("")
    return "\n".join(lines)


def cand_case() -> str:
    lines = [HEADER, "// {piece[2:0], dense index[5:0]} -> candidate_id (10*rotation + x).", ""]
    for pid in range(7):
        ids = candidate_ids(pid)
        for j, cid in enumerate(ids):
            lines.append(f"    9'b{pid:03b}_{j:06b}: cand_id_o = 6'd{cid};")
    lines.append("")
    lines.append("// dense list lengths per piece")
    lines.append("// " + ", ".join(f"{PIECE_NAMES[p]}={len(candidate_ids(p))}" for p in range(7)))
    lines.append("")
    return "\n".join(lines)


def cand_count_case() -> str:
    lines = [HEADER, "// piece[2:0] -> dense candidate count", ""]
    for pid in range(7):
        lines.append(f"    3'd{pid}: count_o = 6'd{len(candidate_ids(pid))};")
    lines.append("")
    return "\n".join(lines)


def main(check: bool = False) -> int:
    outputs = {
        ROOT / "tests" / "fixtures" / "shapes.json": json.dumps(shapes_doc(), indent=1) + "\n",
        ROOT / "rtl" / "generated" / "shape_case.svh": shape_case(),
        ROOT / "rtl" / "generated" / "cand_case.svh": cand_case(),
        ROOT / "rtl" / "generated" / "cand_count_case.svh": cand_count_case(),
    }
    changed = []
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        old = path.read_text() if path.is_file() else None
        if old != text:
            changed.append(path)
            if not check:
                path.write_text(text)
    if check and changed:
        print("generated files are stale:", *[str(p.relative_to(ROOT)) for p in changed])
        return 1
    print(f"generated {len(outputs)} files ({len(changed)} changed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(check="--check" in sys.argv))
